#!/usr/bin/env bash

[ -z "${DEBUG}" ] || set -ex

ANYRC_ENV='docker'

init() {
  DOCKER_OPTS=''
  while [[ -n "$1" ]]; do
    case "$1" in
      -e=* | --env=* | -u=* | --user=* | -w=* | --workdir=* )
        DOCKER_OPTS="${DOCKER_OPTS} $1"; ;;
      -e | --env | -u | --user | -w | --workdir )
        DOCKER_OPTS="${DOCKER_OPTS} $1 $2"; shift ;;
      -* )
        DOCKER_OPTS="${DOCKER_OPTS} $1"; ;;
      * )
        if [ -z "${DOCKER_CONTAINER:+_}" ]; then
          DOCKER_CONTAINER="$1"
        elif [ -z ${REMOTE_SHELL:+_} ]; then
          REMOTE_SHELL="$1"
        fi; ;;
    esac
    shift
  done
  if [ -z "${DOCKER_CONTAINER:+_}" ] || [ -z "${REMOTE_SHELL:+_}" ]; then
    exit 1
  fi
}

mk_tmp_dir() {
  TMP_DIR="$(docker exec ${DOCKER_OPTS} ${DOCKER_CONTAINER} mktemp -d)"
}

transfer() {
  # Transfer .anyrc
  docker cp -L "${ANYRC_DANYRC}" "${DOCKER_CONTAINER}:${TMP_DIR}/${DANYRC_NAME}"

  if [ -n "${ANYRC_DOCKER_WO_TAR}" ]; then
    # Transfer .anyrc.d
    docker cp -L "${ANYRC_DANYRCD}" "${DOCKER_CONTAINER}:${TMP_DIR}/${DANYRCD_NAME}"

    # Transfer *rc
    local CMD_DIR="$(abs_dirname $0)"
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        docker cp -L "${CMD_DIR}/${cmd}" "${DOCKER_CONTAINER}:${TMP_DIR}/${cmd}"
      fi
    done
  else
    # Transfer .anyrc.d
    tar cz -h -C "${DANYRCD_DIR}" "${DANYRCD_BASE}" \
    | docker exec -i ${DOCKER_OPTS} ${DOCKER_CONTAINER} sh -c "tar xz -C ${TMP_DIR}"

    # Transfer *rc
    local CMD_DIR="$(abs_dirname $0)"
    local RCS=()
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        RCS=("${RCS[@]}" "${cmd}")
      fi
    done
    tar czf - -h -C ${CMD_DIR} "${RCS[@]}" \
    | docker exec -i ${DOCKER_OPTS} "${DOCKER_CONTAINER}" sh -c "tar xz -C ${TMP_DIR}"
  fi
}

connect() {
  docker exec -it ${DOCKER_OPTS} "${DOCKER_CONTAINER}" \
    "${REMOTE_SHELL}" -c "
      export DANYRC_NAME=\"${DANYRC_NAME}\"
      export DANYRCD_NAME=\"${DANYRCD_NAME}\"
      export ANYRC_ROOT=\"${TMP_DIR}\"
      export ANYRC_DANYRC=\"\${ANYRC_ROOT}/\${DANYRC_NAME}\"
      export ANYRC_DANYRCD=\"\${ANYRC_ROOT}/\${DANYRCD_NAME}\"
      export ANYRC_HOME=\"\${ANYRC_DANYRCD}\"
      export SHELL=\$(which \"${REMOTE_SHELL}\")
      export PATH=\"\${PATH}:\${ANYRC_ROOT}\"
      trap \"rm -rf \${ANYRC_ROOT}; exit\" 0
      echo -e \"source \${ANYRC_DANYRC}\\n${REMOTE_SHELL}\" \\
        > \"\${ANYRC_HOME}/${REMOTE_SHELL##*/}rc\"
      source \"\${ANYRC_DANYRC}\"
      [ \"${REMOTE_SHELL##*/}\" = 'bash' ] \
        && bash --rcfile \${ANYRC_DANYRC} \
        || ${REMOTE_SHELL}"
}

source anyrc
