#!/usr/bin/env bash

[ -z "${DEBUG}" ] || set -ex

ANYRC_ENV='docker'

init() {
  DOCKER_CONTAINER="${ARGS[@]:$#-2:1}"
  REMOTE_SHELL="${ARGS[@]:$#-1:1}"
}

mk_tmp_dir() {
  TMP_DIR="$(docker exec ${DOCKER_CONTAINER} mktemp -d)"
}

transfer() {
  # Transfer .anyrc
  docker cp -L "${ANYRC_DANYRC}" "${DOCKER_CONTAINER}:${TMP_DIR}/${DANYRC_NAME}"

  if [ -n "${ANYRC_DOCKER_WO_TAR}" ]; then
    # Transfer .anyrc.d
    docker cp -L "${ANYRC_DANYRCD}" "${DOCKER_CONTAINER}:${TMP_DIR}/${DANYRCD_NAME}"

    # Transfer *rc
    local CMD_DIR="$(abs_dirname $0)"
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        docker cp -L "${CMD_DIR}/${cmd}" "${DOCKER_CONTAINER}:${TMP_DIR}/${cmd}"
      fi
    done
  else
    # Transfer .anyrc.d
    tar czh -C "${DANYRCD_DIR}" "${DANYRCD_BASE}" \
    | docker exec -i ${DOCKER_CONTAINER} sh -c "tar xz -C ${TMP_DIR}"

    # Transfer *rc
    local CMD_DIR=$(abs_dirname $0)
    local RCS=()
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        RCS=("${RCS[@]}" "${cmd}")
      fi
    done
    tar czfh - -C ${CMD_DIR} "${RCS[@]}" \
    | docker exec -i "${DOCKER_CONTAINER}" sh -c "tar xz -C ${TMP_DIR}"
  fi
}

connect() {
  docker exec -it "${DOCKER_CONTAINER}" \
    "${REMOTE_SHELL}" -c "
      export DANYRC_NAME=\"${DANYRC_NAME}\"
      export DANYRCD_NAME=\"${DANYRCD_NAME}\"
      export ANYRC_ROOT=\"${TMP_DIR}\"
      export ANYRC_DANYRC=\"\${ANYRC_ROOT}/\${DANYRC_NAME}\"
      export ANYRC_DANYRCD=\"\${ANYRC_ROOT}/\${DANYRCD_NAME}\"
      export ANYRC_HOME=\"\${ANYRC_DANYRCD}\"
      export SHELL=\$(which \"${REMOTE_SHELL}\")
      export PATH=\"\${PATH}:\${ANYRC_ROOT}\"
      trap \"rm -rf \${ANYRC_ROOT}; exit\" 0
      echo -e \"source \${ANYRC_DANYRC}\\n${REMOTE_SHELL}\" \\
        > \"\${ANYRC_HOME}/${REMOTE_SHELL##*/}rc\"
      source \"\${ANYRC_DANYRC}\"
      [ \"${REMOTE_SHELL##*/}\" = 'bash' ] \
        && bash --rcfile \${ANYRC_DANYRC} \
        || ${REMOTE_SHELL}"
}

source anyrc
