#!/usr/bin/env bash

[ -z "${DEBUG}" ] || set -ex

set -ex

ANYRC_ENV='k8s'

init() {
  K8S_OPTS=''
  while [[ -n "$1" ]]; do
    case "$1" in
      -c=* )
        K8S_OPTS="${K8S_OPTS} $1" ;;
      -c )
        K8S_OPTS="${K8S_OPTS} $1 $2"; shift ;;
      -* )
        K8S_OPTS="${K8S_OPTS} $1" ;;
      * )
        if [ -z "${K8S_POD:+_}" ]; then
         K8S_POD="$1"
        elif [ -z ${REMOTE_SHELL:+_} ]; then
          REMOTE_SHELL="$1"
        fi; ;;
    esac
    shift
  done
  if [ -z "${K8S_POD:+_}" ] || [ -z "${REMOTE_SHELL:+_}" ]; then
    exit 1
  fi
}

mk_tmp_dir() {
  TMP_DIR="$(kubectl exec ${K8S_OPTS} ${K8S_POD} -- mktemp -d)"
}

transfer() {
  # Transfer .anyrc
  kubectl cp "$(readlink -f ${ANYRC_DANYRC})" "${K8S_POD}:${TMP_DIR}/${DANYRC_NAME}"

  if [ ! -z "${ANYRC_K8S_WO_TAR:+_}" ] || [ ! -z "${ANYRC_WO_TAR:+_}" ]; then
    # Transfer .anyrc.d
    kubectl cp "$(readlink -f ${ANYRC_DANYRCD})" "${K8S_POD}:${TMP_DIR}/${DANYRCD_NAME}"

    # Transfer *rc
    local CMD_DIR="$(abs_dirname $0)"
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        kubectl cp "$(readlink -f ${CMD_DIR}/${cmd})" "${K8S_POD}:${TMP_DIR}/${cmd}"
      fi
    done
  else
    # Transfer .anyrc.d
    tar cz -h -C "${DANYRCD_DIR}" "${DANYRCD_BASE}" \
    | kubectl exec -i ${K8S_OPTS} ${K8S_POD} -- tar xz -C "${TMP_DIR}"

    # Transfer *rc
    local CMD_DIR=$(abs_dirname $0)
    local RCS=()
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        RCS=("${RCS[@]}" "${cmd}")
      fi
    done
    tar czf - -h -C ${CMD_DIR} "${RCS[@]}" \
    | kubectl exec -i ${K8S_OPTS} "${K8S_POD}" -- tar xz -C "${TMP_DIR}"
  fi
}

connect() {
  kubectl exec -it ${K8S_OPTS} "${K8S_POD}" \
    -- "${REMOTE_SHELL}" -c "
      export DANYRC_NAME=\"${DANYRC_NAME}\"
      export DANYRCD_NAME=\"${DANYRCD_NAME}\"
      export ANYRC_ROOT=\"${TMP_DIR}\"
      export ANYRC_DANYRC=\"\${ANYRC_ROOT}/\${DANYRC_NAME}\"
      export ANYRC_DANYRCD=\"\${ANYRC_ROOT}/\${DANYRCD_NAME}\"
      export ANYRC_HOME=\"\${ANYRC_DANYRCD}\"
      export SHELL=\$(which \"${REMOTE_SHELL}\")
      export PATH=\"\${PATH}:\${ANYRC_ROOT}\"
      trap \"rm -rf \${ANYRC_ROOT}; exit\" 0
      echo -e \"source \${ANYRC_DANYRC}\\n${REMOTE_SHELL}\" \\
        > \"\${ANYRC_HOME}/${REMOTE_SHELL##*/}rc\"
      source \"\${ANYRC_DANYRC}\"
      [ \"${REMOTE_SHELL##*/}\" = 'bash' ] \
        && bash --rcfile \${ANYRC_DANYRC} \
        || ${REMOTE_SHELL}"
}

source anyrc
