#!/usr/bin/env bash

[ -z "${DEBUG}" ] || set -ex

set -ex

ANYRC_ENV='k8s'

init() {
  K8S_POD="${ARGS[@]:$#-2:1}"
  REMOTE_SHELL="${ARGS[@]:$#-1:1}"
}

mk_tmp_dir() {
  TMP_DIR="$(kubectl exec ${K8S_POD} -- mktemp -d)"
}

transfer() {
  # Transfer .anyrc
  kubectl cp "$(readlink -f ${ANYRC_DANYRC})" "${K8S_POD}:${TMP_DIR}/${DANYRC_NAME}"

  if [ -n "${ANYRC_DOCKER_WO_TAR}" ]; then
    # Transfer .anyrc.d
    kubectl cp "$(readlink -f ${ANYRC_DANYRCD})" "${K8S_POD}:${TMP_DIR}/${DANYRCD_NAME}"

    # Transfer *rc
    local CMD_DIR="$(abs_dirname $0)"
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        kubectl cp "$(readlink -f ${CMD_DIR}/${cmd})" "${K8S_POD}:${TMP_DIR}/${cmd}"
      fi
    done
  else
    # Transfer .anyrc.d
    tar czh -C "${DANYRCD_DIR}" "${DANYRCD_BASE}" \
    | kubectl exec -i ${K8S_POD} -- tar xz -C "${TMP_DIR}"

    # Transfer *rc
    local CMD_DIR=$(abs_dirname $0)
    local RCS=()
    for cmd in "${ANYRC_CMD}" "${ANYRC_CMDS[@]}"; do
      if [ -f "${CMD_DIR}/${cmd}" ]; then
        RCS=("${RCS[@]}" "${cmd}")
      fi
    done
    tar czfh - -C ${CMD_DIR} "${RCS[@]}" \
    | kubectl exec -i "${K8S_POD}" -- tar xz -C "${TMP_DIR}"
  fi
}

connect() {
  kubectl exec -it "${K8S_POD}" \
    -- "${REMOTE_SHELL}" -c "
      export DANYRC_NAME=\"${DANYRC_NAME}\"
      export DANYRCD_NAME=\"${DANYRCD_NAME}\"
      export ANYRC_ROOT=\"${TMP_DIR}\"
      export ANYRC_DANYRC=\"\${ANYRC_ROOT}/\${DANYRC_NAME}\"
      export ANYRC_DANYRCD=\"\${ANYRC_ROOT}/\${DANYRCD_NAME}\"
      export ANYRC_HOME=\"\${ANYRC_DANYRCD}\"
      export SHELL=\$(which \"${REMOTE_SHELL}\")
      export PATH=\"\${PATH}:\${ANYRC_ROOT}\"
      trap \"rm -rf \${ANYRC_ROOT}; exit\" 0
      echo -e \"source \${ANYRC_DANYRC}\\n${REMOTE_SHELL}\" \\
        > \"\${ANYRC_HOME}/${REMOTE_SHELL##*/}rc\"
      source \"\${ANYRC_DANYRC}\"
      [ \"${REMOTE_SHELL##*/}\" = 'bash' ] \
        && bash --rcfile \${ANYRC_DANYRC} \
        || ${REMOTE_SHELL}"
}

source anyrc
