#!/usr/bin/env bash

[ -z "${DEBUG}" ] || set -ex

ANYRC_ENV='ssh'

init() {
  SSH_OPTS=''
  while [[ -n "$1" ]]; do
    case "$1" in
      -b | -c | -D | -E | -e | -F | -I | -i | -J | -L | -l | -m | -O | -o | -p | -Q | -R | -S | -W | -w )
        SSH_OPTS="${SSH_OPTS} $1 $2"; shift ;;
      -* )
        SSH_OPTS="${SSH_OPTS} $1" ;;
      * )
        if [ -z "${SSH_REMOTE:+_}" ]; then
         SSH_REMOTE="$1"
        fi; ;;
    esac
    shift
  done
  if [ -z "${SSH_REMOTE:+_}" ]; then
    ssh ${SSH_OPTS}; exit 1;
  fi
}

mk_tmp_dir() {
  :
}

transfer() {
  :
}

connect() {
  local CMD_DIR="$(abs_dirname $0)"
  ssh -t "${SSH_REMOTE}" ${SSH_OPTS} "\
      export DANYRC_NAME=\"${DANYRC_NAME}\"
      export DANYRCD_NAME=\"${DANYRCD_NAME}\"
      export ANYRC_ROOT=\"\$(mktemp -d)\"
      export ANYRC_DANYRC=\"\${ANYRC_ROOT}/\${DANYRC_NAME}\"
      export ANYRC_DANYRCD=\"\${ANYRC_ROOT}/\${DANYRCD_NAME}\"
      export ANYRC_HOME=\"\${ANYRC_DANYRCD}\"
      export PATH=\"\${ANYRC_ROOT}:\${PATH}\"
      trap \"rm -rf \${ANYRC_ROOT}; exit\" 0
      mkdir -p \${ANYRC_DANYRCD}
      echo $'"$(cat "${ANYRC_DANYRC}" | openssl enc -base64)"' | tr -s ' ' $'\n' | openssl enc -base64 -d > \${ANYRC_DANYRC}
      echo $'"$(tar czf - -h -C ${CMD_DIR} ${ANYRC_CMD} ${ANYRC_CMDS[@]} | openssl enc -base64)"' | tr -s ' ' $'\n' | openssl enc -base64 -d | tar mxzf - -C \${ANYRC_ROOT}
      echo $'"$(tar czf - -h -C ${DANYRCD_DIR} ${DANYRCD_BASE} | openssl enc -base64)"' | tr -s ' ' $'\n' | openssl enc -base64 -d | tar mxzf - -C \${ANYRC_ROOT}
      source \${ANYRC_DANYRC}
      [ \"\${SHELL##*/}\" = 'bash' ] \
        && bash --rcfile \${ANYRC_DANYRC} \
        || \${SHELL}"
}

source anyrc
